---
# cchq user is created in supervisor role
- name: Add dev group
  become: yes
  group: name="{{ dev_group }}" state=present

- name: Add users for current devs
  become: yes
  user: name="{{ item }}" state=present shell=/bin/bash groups={{ dev_group }}
  with_items: '{{ dev_users.present }}'

- name: Add public keys for current devs
  become: yes
  authorized_key: user="{{ item }}" state=present key="{{ lookup('file', 'vars/users/' ~ item ~ '.pub') }}" exclusive=yes
  with_items: '{{ dev_users.present }}'
  ignore_errors: "{{ ansible_check_mode }}"

- name: Add MSP user sudo user
  user: name=msp state=present shell=/bin/bash groups="sudo" password="{{ msp_user_password_sha_512 }}"
  when: msp_user|default(false)

- name: Add public key for MSP
  become: yes
  authorized_key: user=msp state=present key="{{ lookup('file', 'vars/{{ deploy_env }}/msp.pub') }}"
  when: msp_user|default(false)
  ignore_errors: "{{ ansible_check_mode }}"

- name: Add ansible user
  user: name=ansible state=present shell=/bin/bash groups="sudo" password="{{ ansible_user_password_sha_512 }}"

- name: Authorize current devs to login as ansible
  become: yes
  authorized_key: user=ansible state=present key="{{ lookup('file', 'vars/users/' ~ item ~ '.pub') }}"
  with_items: '{{ dev_users.present }}'

- name: De-authorize ansible pubkey
  become: yes
  authorized_key: user=ansible state=absent key="{{ lookup('file', 'vars/users/ansible.pub') }}"

- name: find supervisorctl path
  shell: 'dirname "$(which supervisorctl)"'
  register: dirname_which_supervisorctl
  changed_when: false
  check_mode: no

- import_tasks: remove_users.yml
  when: dev_users.absent

- name: Copy sudoers file
  become: yes
  template: src=sudoers.j2 dest=/etc/sudoers.d/cchq validate='visudo -cf %s' owner=root group=root mode=0440
