---
language: python
python: "2.7"

env:
  global:
    - ANSIBLE_ROLES_PATH="~/.ansible/roles"
    - TRAVIS_TEST=1
  matrix:
    - TEST=main
    - TEST=prove-deploy

matrix:
  allow_failures:
    - env: TEST=prove-deploy

before_install:
  # Make sure everything's up to date.
  - sudo apt-get update -qq

install:
  - "source control/init.sh"
  - pip install -r test_requirements.txt

script:
  - ".travis/tests.sh"
