---
- name: Add mosh apt repo
  apt_repository: repo='ppa:keithw/mosh' state=present
  register: add_mosh_repo

- name: Add git apt repo
  apt_repository: repo='ppa:git-core/ppa' state=present
  register: add_git_repo

# ubuntu16: no need for nodejs repo
# http://stackoverflow.com/a/16303380/835696
- name: Add git nodejs repo
  apt_repository: repo='ppa:chris-lea/node.js' state=absent
  register: add_nodejs_repo

# ubuntu16: no need for gradle repo
- name: Add gradle repo
  apt_repository: repo='ppa:cwchien/gradle' state=absent
  register: add_gradle_repo

- name: Add PostreSQL apt repository
  apt_repository: repo='deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_lsb.codename }}-pgdg main' state=present
  register: add_postgres_repo

- name: Add PosgreSQL apt key
  apt_key: url=https://www.postgresql.org/media/keys/ACCC4CF8.asc state=present

- name: Update package list
  apt: update_cache=yes
  when: add_nodejs_repo|changed or add_mosh_repo|changed or add_git_repo|changed or add_postgres_repo|changed or add_gradle_repo|changed

# Install base packages, common to all servers
- name: Install common packages
  apt: name="{{ item }}" state=present
  become: yes
  with_items:
    - build-essential
    - python-pip
    - python-dev
    - python-setuptools
    - python-psycopg2
    - postgresql-client-common
    - postgresql-client-{{ postgresql_version }}
    - libxml2-dev
    - libxslt1-dev
    - git
    - tig # git browser
    - libpq-dev
    - curl
    - htop
    - tmpreaper
    - mailutils
    - ntp
    - nodejs
    - npm
    - at
    - screen
    - sysstat
    - gettext
    - python-software-properties
    - mosh
    - libjpeg-dev
    - libfreetype6-dev
    - gradle
    - ranger  # cmdline file browser
    - libffi-dev  # Required for installing github3py
    - libssl-dev  # Required for pip setup tools
    - tmux
    - unzip
    - zip
    - iotop
    - ncdu # 'du' improved
    - monit # service restarter

# ubuntu16: node -- nodejs
- name: Symlink node to nodejs
  sudo: yes
  file:
    src: /usr/bin/nodejs
    dest: /usr/bin/node
    state: link

- name: Set NPM registry
  command: 'npm config set registry http://registry.npmjs.org/'
  become: yes

- name: Install npm items
  npm: name="{{ item }}" state=present global=yes
  become: yes
  with_items:
    - npm@3.6.0
    - less@2.7.2
    - n@1.3.0
    - bower@1.5.3
    - uglify-js@2.6.1
  tags:
    - npm

- name: Update Node
  command: 'n 0.10.29'
  become: yes

- name: Install pip packages
  pip: name="{{ item }}"
  become: yes
  with_items:
    - virtualenv
    - sh
    - httplib2

- name: Install virtualenv-clone
  become: yes
  pip:
    name: virtualenv-clone
    version: 0.2.6
