---

- name: load configuration
  include_vars: "{{ site_name }}.yml"

- name: Create the site configurations
  become: yes
  template:
    src: site.j2
    dest: "/etc/nginx/sites-available/{{ item.server.file_name }}"
    owner: "{{ cchq_user }}"
    group: "{{ cchq_user }}"
    mode: "u=rw,g=rw,o=r"
  with_items: "{{ nginx_sites|default([]) }}"

- name: Create the links to enable site configurations
  become: yes
  file: path="/etc/nginx/sites-enabled/{{ item.server['file_name'] }}" state=link src="/etc/nginx/sites-available/{{ item.server['file_name'] }}"
  with_items: "{{ nginx_sites|default([]) }}"
  when: not ansible_check_mode
