---
- name: Install Vim
  sudo: yes
  apt: name=vim state=present

- name: Install Emacs
  sudo: yes
  apt: name=emacs24 state=present

- name: Include vimrc
  sudo: yes
  copy:
    src: vimrc
    dest: /etc/vimrc
    owner: root
    group: root
    mode: 0644
