---
- name: Install Vim
  become: yes
  apt: name=vim state=present

- name: Install Emacs
  become: yes
  apt: name=emacs23 state=present
  when: ansible_distribution_version == '14.04'

- name: Install Emacs
  become: yes
  apt: name=emacs24 state=present
  when: ansible_distribution_version == '16.04'

- name: Include vimrc
  become: yes
  copy:
    src: vimrc
    dest: /etc/vimrc
    owner: root
    group: root
    mode: 0644
